<a href="https://colab.research.google.com/github/Meshack-millan/Coffee-sales-Dashboard/blob/main/project2_Analysis_of_Car_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Working on Real Project with Python

Cars Dataset
Here. The data of different cars with their specifications.
This data is available as csv file. We are going to analyze this data set using pandas DataFrame

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv(r"/project2carsdata.csv")

In [4]:
df.head()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0

Q1. Instructions
Find all information about the dataframe

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 432 entries, 0 to 431
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Make         428 non-null    object
 1   Model        428 non-null    object
 2   Type         428 non-null    object
 3   Origin       428 non-null    object
 4   DriveTrain   428 non-null    object
 5   MSRP         428 non-null    object
 6   Invoice      428 non-null    object
 7   EngineSize   428 non-null    float64
 8   Cylinders    426 non-null    float64
 9   Horsepower   428 non-null    float64
 10  MPG_City     428 non-null    float64
 11  MPG_Highway  428 non-null    float64
 12  Weight       428 non-null    float64
 13  Wheelbase    428 non-null    float64
 14  Length       428 non-null    float64
dtypes: float64(8), object(7)
memory usage: 50.8+ KB

In [6]:
df.shape

(432, 15)

1) Instruction  (For Data Cleaning)
Find all null value in the dataset. If there is any null value in any column , then fill it with the mean of that column

In [7]:
df.isnull().sum()

Make           4
Model          4
Type           4
Origin         4
DriveTrain     4
MSRP           4
Invoice        4
EngineSize     4
Cylinders      6
Horsepower     4
MPG_City       4
MPG_Highway    4
Weight         4
Wheelbase      4
Length         4
dtype: int64

In [8]:
pd.set_option('display.max_rows', None)

In [19]:
df.head()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0

In [21]:
df.isnull().sum()

Make           0
Model          0
Type           0
Origin         0
DriveTrain     0
MSRP           0
Invoice        0
EngineSize     0
Cylinders      2
Horsepower     0
MPG_City       0
MPG_Highway    0
Weight         0
Wheelbase      0
Length         0
dtype: int64

In [12]:
df.drop(index=[30,39,161,173],inplace=True)

In [13]:
df.isnull().sum()

Make           0
Model          0
Type           0
Origin         0
DriveTrain     0
MSRP           0
Invoice        0
EngineSize     0
Cylinders      2
Horsepower     0
MPG_City       0
MPG_Highway    0
Weight         0
Wheelbase      0
Length         0
dtype: int64

In [14]:
df.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       422, 423, 424, 425, 426, 427, 428, 429, 430, 431],
      dtype='int64', length=428)

In [18]:
df.reset_index().head()

,index,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0

In [22]:
df.head(5)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0

In [23]:
df.isnull().sum()

Make           0
Model          0
Type           0
Origin         0
DriveTrain     0
MSRP           0
Invoice        0
EngineSize     0
Cylinders      2
Horsepower     0
MPG_City       0
MPG_Highway    0
Weight         0
Wheelbase      0
Length         0
dtype: int64

In [24]:
df['Cylinders'].fillna(df['Cylinders'].mean(),inplace=True)

<ipython-input-24-46eb511b3bc5>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cylinders'].fillna(df['Cylinders'].mean(),inplace=True)

In [25]:
df.isnull().sum()

Make           0
Model          0
Type           0
Origin         0
DriveTrain     0
MSRP           0
Invoice        0
EngineSize     0
Cylinders      0
Horsepower     0
MPG_City       0
MPG_Highway    0
Weight         0
Wheelbase      0
Length         0
dtype: int64

2) check what are the different types of Make are there in our dataset. And what is the count (occurrence) of each make in the data

In [26]:
df.dtypes

Make            object
Model           object
Type            object
Origin          object
DriveTrain      object
MSRP            object
Invoice         object
EngineSize     float64
Cylinders      float64
Horsepower     float64
MPG_City       float64
MPG_Highway    float64
Weight         float64
Wheelbase      float64
Length         float64
dtype: object

In [27]:
df['Make'].value_counts()

Make
Toyota           28
Chevrolet        27
Mercedes-Benz    26
Ford             23
BMW              20
Audi             19
Nissan           17
Honda            17
Chrysler         15
Volkswagen       15
Mitsubishi       13
Dodge            13
Volvo            12
Hyundai          12
Jaguar           12
Subaru           11
Kia              11
Pontiac          11
Mazda            11
Lexus            11
Buick             9
Mercury           9
Lincoln           9
Cadillac          8
GMC               8
Saturn            8
Suzuki            8
Infiniti          8
Acura             7
Saab              7
Porsche           7
Land Rover        3
Oldsmobile        3
Jeep              3
Isuzu             2
MINI              2
Scion             2
Hummer            1
Name: count, dtype: int64

3) show all the records where Origin is Asia or Europe

In [31]:
df[(df['Origin']=="Asia") | (df['Origin']=="Europe")]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.000000,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.000000,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.000000,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.000000,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.000000,225.0,18.0,24.0,3880.0,115.0,197.0
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.000000,225.0,18.0,24.0,3893.0,115.0,197.0
6,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765","$79,978",3.2,6.000000,290.0,17.0,24.0,3153.0,100.0,174.0
7,Audi,A4 1.8T 4dr,Sedan,Europe,Front,"$25,940","$23,508",1.8,4.000000,170.0,22.0,31.0,3252.0,104.0,179.0
8,Audi,A41.8T convertible 2dr,Sedan,Europe,Front,"$35,940","$32,506",1.8,4.000000,170.0,23.0,30.0,3638.0,105.0,180.0
9,Audi,A4 3.0 4dr,Sedan,Europe,Front,"$31,840","$28,846",3.0,6.000000,220.0,20.0,28.0,3462.0,104.0,179.0
10,Audi,A4 3.0 Quattro 4dr manual,Sedan,Europe,All,"$33,430","$30,366",3.0,6.000000,220.0,17.0,26.0,3583.0,104.0,179.0
11,Audi,A4 3.0 Quattro 4dr auto,Sedan,Europe,All,"$34,480","$31,388",3.0,6.000000,220.0,18.0,25.0,3627.0,104.0,179.0
12,Audi,A6 3.0 4dr,Sedan,Europe,Front,"$36,640","$33,129",3.0,6.000000,220.0,20.0,27.0,3561.0,109.0,192.0
13,Audi,A6 3.0 Quattro 4dr,Sedan,Europe,All,"$39,640","$35,992",3.0,6.000000,220.0,18.0,25.0,3880.0,109.0,192.0
14,Audi,A4 3.0 convertible 2dr,Sedan,Europe,Front,"$42,490","$38,325",3.0,6.000000,220.0,20.0,27.0,3814.0,105.0,180.0
15,Audi,A4 3.0 Quattro convertible 2dr,Sedan,Europe,All,"$44,240","$40,075",3.0,6.000000,220.0,18.0,25.0,4013.0,105.0,180.0
16,Audi,A6 2.7 Turbo Quattro 4dr,Sedan,Europe,All,"$42,840","$38,840",2.7,6.000000,250.0,18.0,25.0,3836.0,109.0,192.0
17,Audi,A6 4.2 Quattro 4dr,Sedan,Europe,All,"$49,690","$44,936",4.2,8.000000,300.0,17.0,24.0,4024.0,109.0,193.0
18,Audi,A8 L Quattro 4dr,Sedan,Europe,All,"$69,190","$64,740",4.2,8.000000,330.0,17.0,24.0,4399.0,121.0,204.0
19,Audi,S4 Quattro 4dr,Sedan,Europe,All,"$48,040","$43,556",4.2,8.000000,340.0,14.0,20.0,3825.0,104.0,179.0
20,Audi,RS 6 4dr,Sports,Europe,Front,"$84,600","$76,417",4.2,8.000000,450.0,15.0,22.0,4024.0,109.0,191.0
21,Audi,TT 1.8 convertible 2dr (coupe),Sports,Europe,Front,"$35,940","$32,512",1.8,4.000000,180.0,20.0,28.0,3131.0,95.0,159.0
22,Audi,TT 1.8 Quattro 2dr (convertible),Sports,Europe,All,"$37,390","$33,891",1.8,4.000000,225.0,20.0,28.0,2921.0,96.0,159.0
23,Audi,TT 3.2 coupe 2dr (convertible),Sports,Europe,All,"$40,590","$36,739",3.2,6.000000,250.0,21.0,29.0,3351.0,96.0,159.0
24,Audi,A6 3.0 Avant Quattro,Wagon,Europe,All,"$40,840","$37,060",3.0,6.000000,220.0,18.0,25.0,4035.0,109.0,192.0
25,Audi,S4 Avant Quattro,Wagon,Europe,All,"$49,090","$44,446",4.2,8.000000,340.0,15.0,21.0,3936.0,104.0,179.0
26,BMW,X3 3.0i,SUV,Europe,All,"$37,000","$33,873",3.0,6.000000,225.0,16.0,23.0,4023.0,110.0,180.0
27,BMW,X5 4.4i,SUV,Europe,All,"$52,195","$47,720",4.4,8.000000,325.0,16.0,22.0,4824.0,111.0,184.0
28,BMW,325i 4dr,Sedan,Europe,Rear,"$28,495","$26,155",2.5,6.000000,184.0,20.0,29.0,3219.0,107.0,176.0
29,BMW,325Ci 2dr,Sedan,Europe,Rear,"$30,795","$28,245",2.5,6.000000,184.0,20.0,29.0,3197.0,107.0,177.0
31,BMW,325Ci convertible 2dr,Sedan,Europe,Rear,"$37,995","$34,800",2.5,6.000000,184.0,19.0,27.0,3560.0,107.0,177.0
32,BMW,325xi 4dr,Sedan,Europe,All,"$30,245","$27,745",2.5,6.000000,184.0,19.0,27.0,3461.0,107.0,176.0
33,BMW,330i 4dr,Sedan,Europe,Rear,"$35,495","$32,525",3.0,6.000000,225.0,20.0,30.0,3285.0,107.0,176.0
34,BMW,330Ci 2dr,Sedan,Europe,Rear,"$36,995","$33,890",3.0,6.000000,225.0,20.0,30.0,3285.0,107.0,176.0
35,BMW,330xi 4dr,Sedan,Europe,All,"$37,245","$34,115",3.0,6.000000,225.0,20.0,29.0,3483.0,107.0,176.0
36,BMW,525i 4dr,Sedan,Europe,Rear,"$39,995","$36,620",2.5,6.000000,184.0,19.0,28.0,3428.0,114.0,191.0
37,BMW,330Ci convertible 2dr,Sedan,Europe,Rear,"$44,295","$40,530",3.0,6.000000,225.0,19.0,28.0,3616.0,107.0,177.0
38,BMW,530i 4dr,Sedan,Europe,Rear,"$44,995","$41,170",3.0,6.000000,225.0,20.0,30.0,3472.0,114.0,191.0
40,BMW,545iA 4dr,Sedan,Europe,Rear,"$54,995","$50,270",4.4,8.000000,325.0,18.0,26.0,3814.0,114.0,191.0
41,BMW,745i 4dr,Sedan,Europe,Rear,"$69,195","$63,190",4.4,8.000000,325.0,18.0,26.0,4376.0,118.0,198.0
42,BMW,745Li 4dr,Sedan,Europe,Rear,"$73,195","$66,830",4.4,8.000000,325.0,18.0,26.0,4464.0,123.0,204.0
43,BMW,M3 coupe 2dr,Sports,Europe,Rear,"$48,195","$44,170",3.2,6.000000,333.0,16.0,24.0,3415.0,108.0,177.0
44,BMW,M3 convertible 2dr,Sports,Europe,Rear,"$56,595","$51,815",3.2,6.000000,333.0,16.0,23.0,3781.0,108.0,177.0
45,BMW,Z4 convertible 2.5i 2dr,Sports,Europe,Rear,"$33,895","$31,065",2.5,6.000000,184.0,20.0,28.0,2932.0,98.0,161.0
46,BMW,Z4 convertible 3.0i 2dr,Sports,Europe,Rear,"$41,045","$37,575",3.0,6.000000,225.0,21.0,29.0,2998.0,98.0,161.0
47,BMW,325xi Sport,Wagon,Europe,All,"$32,845","$30,110",2.5,6.000000,184.0,19.0,26.0,3594.0,107.0,176.0
151,Honda,Civic Hybrid 4dr manual (gas/electric),Hybrid,Asia,Front,"$20,140","$18,451",1.4,4.000000,93.0,46.0,51.0,2732.0,103.0,175.0
152,Honda,Insight 2dr (gas/electric),Hybrid,Asia,Front,"$19,110","$17,911",2.0,3.000000,73.0,60.0,66.0,1850.0,95.0,155.0
153,Honda,Pilot LX,SUV,Asia,All,"$27,560","$24,843",3.5,6.000000,240.0,17.0,22.0,4387.0,106.0,188.0
154,Honda,CR-V LX,SUV,Asia,All,"$19,860","$18,419",2.4,4.000000,160.0,21.0,25.0,3258.0,103.0,179.0
155,Honda,Element LX,SUV,Asia,All,"$18,690","$17,334",2.4,4.000000,160.0,21.0,24.0,3468.0,101.0,167.0
156,Honda,Civic DX 2dr,Sedan,Asia,Front,"$13,270","$12,175",1.7,4.000000,115.0,32.0,38.0,2432.0,103.0,175.0
157,Honda,Civic HX 2dr,Sedan,Asia,Front,"$14,170","$12,996",1.7,4.000000,117.0,36.0,44.0,2500.0,103.0,175.0
158,Honda,Civic LX 4dr,Sedan,Asia,Front,"$15,850","$14,531",1.7,4.000000,115.0,32.0,38.0,2513.0,103.0,175.0
159,Honda,Accord LX 2dr,Sedan,Asia,Front,"$19,860","$17,924",2.4,4.000000,160.0,26.0,34.0,2994.0,105.0,188.0
160,Honda,Accord EX 2dr,Sedan,Asia,Front,"$22,260","$20,080",2.4,4.000000,160.0,26.0,34.0,3047.0,105.0,188.0
162,Honda,Civic EX 4dr,Sedan,Asia,Front,"$17,750","$16,265",1.7,4.000000,127.0,32.0,37.0,2601.0,103.0,175.0
163,Honda,Civic Si 2dr hatch,Sedan,Asia,Front,"$19,490","$17,849",2.0,4.000000,160.0,26.0,30.0,2782.0,101.0,166.0
164,Honda,Accord LX V6 4dr,Sedan,Asia,Front,"$23,760","$21,428",3.0,6.000000,240.0,21.0,30.0,3349.0,108.0,190.0
165,Honda,Accord EX V6 2dr,Sedan,Asia,Front,"$26,960","$24,304",3.0,6.000000,240.0,21.0,30.0,3294.0,105.0,188.0
166,Honda,Odyssey LX,Sedan,Asia,Front,"$24,950","$22,498",3.5,6.000000,240.0,18.0,25.0,4310.0,118.0,201.0
167,Honda,Odyssey EX,Sedan,Asia,Front,"$27,450","$24,744",3.5,6.000000,240.0,18.0,25.0,4365.0,118.0,201.0
168,Honda,S2000 convertible 2dr,Sports,Asia,Rear,"$33,260","$29,965",2.2,4.000000,240.0,20.0,25.0,2835.0,95.0,162.0
170,Hyundai,Santa Fe GLS,SUV,Asia,Front,"$21,589","$20,201",2.7,6.000000,173.0,20.0,26.0,3549.0,103.0,177.0
171,Hyundai,Accent 2dr hatch,Sedan,Asia,Front,"$10,539","$10,107",1.6,4.000000,103.0,29.0,33.0,2255.0,96.0,167.0
172,Hyundai,Accent GL 4dr,Sedan,Asia,Front,"$11,839","$11,116",1.6,4.000000,103.0,29.0,33.0,2290.0,96.0,167.0
174,Hyundai,Accent GT 2dr hatch,Sedan,Asia,Front,"$11,939","$11,209",1.6,4.000000,103.0,29.0,33.0,2339.0,96.0,167.0
175,Hyundai,Elantra GLS 4dr,Sedan,Asia,Front,"$13,839","$12,781",2.0,4.000000,138.0,26.0,34.0,2635.0,103.0,178.0
176,Hyundai,Elantra GT 4dr,Sedan,Asia,Front,"$15,389","$14,207",2.0,4.000000,138.0,26.0,34.0,2635.0,103.0,178.0
177,Hyundai,Elantra GT 4dr hatch,Sedan,Asia,Front,"$15,389","$14,207",2.0,4.000000,138.0,26.0,34.0,2698.0,103.0,178.0
178,Hyundai,Sonata GLS 4dr,Sedan,Asia,Front,"$19,339","$17,574",2.7,6.000000,170.0,19.0,27.0,3217.0,106.0,187.0
179,Hyundai,Sonata LX 4dr,Sedan,Asia,Front,"$20,339","$18,380",2.7,6.000000,170.0,19.0,27.0,3217.0,106.0,187.0
180,Hyundai,XG350 4dr,Sedan,Asia,Front,"$24,589","$22,055",3.5,6.000000,194.0,17.0,26.0,3651.0,108.0,192.0
181,Hyundai,XG350 L 4dr,Sedan,Asia,Front,"$26,189","$23,486",3.5,6.000000,194.0,17.0,26.0,3651.0,108.0,192.0
182,Hyundai,Tiburon GT V6 2dr,Sports,Asia,Front,"$18,739","$17,101",2.7,6.000000,172.0,19.0,26.0,3023.0,100.0,173.0
183,Infiniti,G35 4dr,Sedan,Asia,Rear,"$28,495","$26,157",3.5,6.000000,260.0,18.0,26.0,3336.0,112.0,187.0
184,Infiniti,G35 Sport Coupe 2dr,Sedan,Asia,Rear,"$29,795","$27,536",3.5,6.000000,280.0,18.0,26.0,3416.0,112.0,182.0
185,Infiniti,G35 4dr,Sedan,Asia,All,"$32,445","$29,783",3.5,6.000000,260.0,18.0,26.0,3677.0,112.0,187.0
186,Infiniti,I35 4dr,Sedan,Asia,Front,"$31,145","$28,320",3.5,6.000000,255.0,19.0,26.0,3306.0,108.0,194.0
187,Infiniti,M45 4dr,Sedan,Asia,Rear,"$42,845","$38,792",4.5,8.000000,340.0,17.0,23.0,3851.0,110.0,197.0
188,Infiniti,Q45 Luxury 4dr,Sedan,Asia,Rear,"$52,545","$47,575",4.5,8.000000,340.0,17.0,23.0,3977.0,113.0,200.0
189,Infiniti,FX35,Wagon,Asia,Rear,"$34,895","$31,756",3.5,6.000000,280.0,16.0,22.0,4056.0,112.0,189.0
190,Infiniti,FX45,Wagon,Asia,All,"$36,395","$33,121",4.5,8.000000,315.0,15.0,19.0,4309.0,112.0,189.0
191,Isuzu,Ascender S,SUV,Asia,All,"$31,849","$29,977",4.2,6.000000,275.0,15.0,20.0,4967.0,129.0,208.0
192,Isuzu,Rodeo S,SUV,Asia,Front,"$20,449","$19,261",3.2,6.000000,193.0,17.0,21.0,3836.0,106.0,178.0
193,Jaguar,X-Type 2.5 4dr,Sedan,Europe,All,"$29,995","$27,355",2.5,6.000000,192.0,18.0,26.0,3428.0,107.0,184.0
194,Jaguar,X-Type 3.0 4dr,Sedan,Europe,All,"$33,995","$30,995",3.0,6.000000,227.0,18.0,25.0,3516.0,107.0,184.0
195,Jaguar,S-Type 3.0 4dr,Sedan,Europe,Rear,"$43,895","$40,004",3.0,6.000000,235.0,18.0,26.0,3777.0,115.0,192.0
196,Jaguar,S-Type 4.2 4dr,Sedan,Europe,Rear,"$49,995","$45,556",4.2,8.000000,294.0,18.0,28.0,3874.0,115.0,192.0
197,Jaguar,S-Type R 4dr,Sedan,Europe,Rear,"$63,120","$57,499",4.2,8.000000,390.0,17.0,24.0,4046.0,115.0,192.0
198,Jaguar,Vanden Plas 4dr,Sedan,Europe,Rear,"$68,995","$62,846",4.2,8.000000,294.0,18.0,28.0,3803.0,119.0,200.0
199,Jaguar,XJ8 4dr,Sedan,Europe,Rear,"$59,995","$54,656",4.2,8.000000,294.0,18.0,28.0,3803.0,119.0,200.0
200,Jaguar,XJR 4dr,Sedan,Europe,Rear,"$74,995","$68,306",4.2,8.000000,390.0,17.0,24.0,3948.0,119.0,200.0
201,Jaguar,XK8 coupe 2dr,Sports,Europe,Rear,"$69,995","$63,756",4.2,8.000000,294.0,18.0,26.0,3779.0,102.0,187.0
202,Jaguar,XK8 convertible 2dr,Sports,Europe,Rear,"$74,995","$68,306",4.2,8.000000,294.0,18.0,26.0,3980.0,102.0,187.0
203,Jaguar,XKR coupe 2dr,Sports,Europe,Rear,"$81,995","$74,676",4.2,8.000000,390.0,16.0,23.0,3865.0,102.0,187.0
204,Jaguar,XKR convertible 2dr,Sports,Europe,Rear,"$86,995","$79,226",4.2,8.000000,390.0,16.0,23.0,4042.0,102.0,187.0
208,Kia,Sorento LX,SUV,Asia,Front,"$19,635","$18,630",3.5,6.000000,192.0,16.0,19.0,4112.0,107.0,180.0
209,Kia,Optima LX 4dr,Sedan,Asia,Front,"$16,040","$14,910",2.4,4.000000,138.0,23.0,30.0,3281.0,106.0,186.0
210,Kia,Rio 4dr manual,Sedan,Asia,Front,"$10,280","$9,875",1.6,4.000000,104.0,26.0,33.0,2403.0,95.0,167.0
211,Kia,Rio 4dr auto,Sedan,Asia,Front,"$11,155","$10,705",1.6,4.000000,104.0,25.0,32.0,2458.0,95.0,167.0
212,Kia,Spectra 4dr,Sedan,Asia,Front,"$12,360","$11,630",1.8,4.000000,124.0,24.0,32.0,2661.0,101.0,178.0
213,Kia,Spectra GS 4dr hatch,Sedan,Asia,Front,"$13,580","$12,830",1.8,4.000000,124.0,24.0,32.0,2686.0,101.0,178.0
214,Kia,Spectra GSX 4dr hatch,Sedan,Asia,Front,"$14,630","$13,790",1.8,4.000000,124.0,24.0,32.0,2697.0,101.0,178.0
215,Kia,Optima LX V6 4dr,Sedan,Asia,Front,"$18,435","$16,850",2.7,6.000000,170.0,20.0,27.0,3279.0,106.0,186.0
216,Kia,Amanti 4dr,Sedan,Asia,Front,"$26,000","$23,764",3.5,6.000000,195.0,17.0,25.0,4021.0,110.0,196.0
217,Kia,Sedona LX,Sedan,Asia,Front,"$20,615","$19,400",3.5,6.000000,195.0,16.0,22.0,4802.0,115.0,194.0
218,Kia,Rio Cinco,Wagon,Asia,Front,"$11,905","$11,410",1.6,4.000000,104.0,26.0,33.0,2447.0,95.0,167.0
219,Land Rover,Range Rover HSE,SUV,Europe,All,"$72,250","$65,807",4.4,8.000000,282.0,12.0,16.0,5379.0,113.0,195.0
220,Land Rover,Discovery SE,SUV,Europe,All,"$39,250","$35,777",4.6,8.000000,217.0,12.0,16.0,4576.0,100.0,185.0
221,Land Rover,Freelander SE,SUV,Europe,All,"$25,995","$23,969",2.5,6.000000,174.0,18.0,21.0,3577.0,101.0,175.0
222,Lexus,GX 470,SUV,Asia,All,"$45,700","$39,838",4.7,8.000000,235.0,15.0,19.0,4740.0,110.0,188.0
223,Lexus,LX 470,SUV,Asia,All,"$64,800","$56,455",4.7,8.000000,235.0,13.0,17.0,5590.0,112.0,193.0
224,Lexus,RX 330,SUV,Asia,All,"$39,195","$34,576",3.3,6.000000,230.0,18.0,24.0,4065.0,107.0,186.0
225,Lexus,ES 330 4dr,Sedan,Asia,Front,"$32,350","$28,755",3.3,6.000000,225.0,20.0,29.0,3460.0,107.0,191.0
226,Lexus,IS 300 4dr manual,Sedan,Asia,Rear,"$31,045","$27,404",3.0,6.000000,215.0,18.0,25.0,3255.0,105.0,177.0
227,Lexus,IS 300 4dr auto,Sedan,Asia,Rear,"$32,415","$28,611",3.0,6.000000,215.0,18.0,24.0,3285.0,105.0,177.0
228,Lexus,GS 300 4dr,Sedan,Asia,Rear,"$41,010","$36,196",3.0,6.000000,220.0,18.0,25.0,3649.0,110.0,189.0
229,Lexus,GS 430 4dr,Sedan,Asia,Rear,"$48,450","$42,232",4.3,8.000000,300.0,18.0,23.0,3715.0,110.0,189.0
230,Lexus,LS 430 4dr,Sedan,Asia,Rear,"$55,750","$48,583",4.3,8.000000,290.0,18.0,25.0,3990.0,115.0,197.0
231,Lexus,SC 430 convertible 2dr,Sports,Asia,Rear,"$63,200","$55,063",4.3,8.000000,300.0,18.0,23.0,3840.0,103.0,178.0
232,Lexus,IS 300 SportCross,Wagon,Asia,Rear,"$32,455","$28,647",3.0,6.000000,215.0,18.0,24.0,3410.0,105.0,177.0
242,MINI,Cooper,Sedan,Europe,Front,"$16,999","$15,437",1.6,4.000000,115.0,28.0,37.0,2524.0,97.0,143.0
243,MINI,Cooper S,Sedan,Europe,Front,"$19,999","$18,137",1.6,4.000000,163.0,25.0,34.0,2678.0,97.0,144.0
244,Mazda,Tribute DX 2.0,SUV,Asia,All,"$21,087","$19,742",2.0,4.000000,130.0,22.0,25.0,3091.0,103.0,173.0
245,Mazda,Mazda3 i 4dr,Sedan,Asia,Front,"$15,500","$14,525",2.0,4.000000,148.0,26.0,34.0,2696.0,104.0,178.0
246,Mazda,Mazda3 s 4dr,Sedan,Asia,Front,"$17,200","$15,922",2.3,4.000000,160.0,25.0,31.0,2762.0,104.0,179.0
247,Mazda,Mazda6 i 4dr,Sedan,Asia,Front,"$19,270","$17,817",2.3,4.000000,160.0,24.0,32.0,3042.0,105.0,187.0
248,Mazda,MPV ES,Sedan,Asia,Front,"$28,750","$26,600",3.0,6.000000,200.0,18.0,25.0,3812.0,112.0,188.0
249,Mazda,MX-5 Miata convertible 2dr,Sports,Asia,Rear,"$22,388","$20,701",1.8,4.000000,142.0,23.0,28.0,2387.0,89.0,156.0
250,Mazda,MX-5 Miata LS convertible 2dr,Sports,Asia,Rear,"$25,193","$23,285",1.8,4.000000,142.0,23.0,28.0,2387.0,89.0,156.0
251,Mazda,RX-8 4dr automatic,Sports,Asia,Rear,"$25,700","$23,794",1.3,5.807512,197.0,18.0,25.0,3053.0,106.0,174.0
252,Mazda,RX-8 4dr manual,Sports,Asia,Rear,"$27,200","$25,179",1.3,5.807512,238.0,18.0,24.0,3029.0,106.0,174.0
253,Mazda,B2300 SX Regular Cab,Truck,Asia,Rear,"$14,840","$14,070",2.3,4.000000,143.0,24.0,29.0,2960.0,112.0,188.0
254,Mazda,B4000 SE Cab Plus,Truck,Asia,All,"$22,350","$20,482",4.0,6.000000,207.0,15.0,19.0,3571.0,126.0,203.0
255,Mercedes-Benz,G500,SUV,Europe,All,"$76,870","$71,540",5.0,8.000000,292.0,13.0,14.0,5423.0,112.0,186.0
256,Mercedes-Benz,ML500,SUV,Europe,All,"$46,470","$43,268",5.0,8.000000,288.0,14.0,17.0,4874.0,111.0,183.0
257,Mercedes-Benz,C230 Sport 2dr,Sedan,Europe,Rear,"$26,060","$24,249",1.8,4.000000,189.0,22.0,30.0,3250.0,107.0,178.0
258,Mercedes-Benz,C320 Sport 2dr,Sedan,Europe,Rear,"$28,370","$26,435",3.2,6.000000,215.0,19.0,26.0,3430.0,107.0,178.0
259,Mercedes-Benz,C240 4dr,Sedan,Europe,Rear,"$32,280","$30,071",2.6,6.000000,168.0,20.0,25.0,3360.0,107.0,178.0
260,Mercedes-Benz,C240 4dr,Sedan,Europe,All,"$33,480","$31,187",2.6,6.000000,168.0,19.0,25.0,3360.0,107.0,178.0
261,Mercedes-Benz,C320 Sport 4dr,Sedan,Europe,Rear,"$35,920","$33,456",3.2,6.000000,215.0,19.0,26.0,3430.0,107.0,178.0
262,Mercedes-Benz,C320 4dr,Sedan,Europe,Rear,"$37,630","$35,046",3.2,6.000000,215.0,20.0,26.0,3450.0,107.0,178.0
263,Mercedes-Benz,C320 4dr,Sedan,Europe,All,"$38,830","$36,162",3.2,6.000000,215.0,19.0,27.0,3450.0,107.0,178.0
264,Mercedes-Benz,C32 AMG 4dr,Sedan,Europe,Rear,"$52,120","$48,522",3.2,6.000000,349.0,16.0,21.0,3540.0,107.0,178.0
265,Mercedes-Benz,CL500 2dr,Sedan,Europe,Rear,"$94,820","$88,324",5.0,8.000000,302.0,16.0,24.0,4085.0,114.0,196.0
266,Mercedes-Benz,CL600 2dr,Sedan,Europe,Rear,"$128,420","$119,600",5.5,12.000000,493.0,13.0,19.0,4473.0,114.0,196.0
267,Mercedes-Benz,CLK320 coupe 2dr (convertible),Sedan,Europe,Rear,"$45,707","$41,966",3.2,6.000000,215.0,20.0,26.0,3770.0,107.0,183.0
268,Mercedes-Benz,CLK500 coupe 2dr (convertible),Sedan,Europe,Rear,"$52,800","$49,104",5.0,8.000000,302.0,17.0,22.0,3585.0,107.0,183.0
269,Mercedes-Benz,E320 4dr,Sedan,Europe,Rear,"$48,170","$44,849",3.2,6.000000,221.0,19.0,27.0,3635.0,112.0,190.0
270,Mercedes-Benz,E500 4dr,Sedan,Europe,Rear,"$57,270","$53,382",5.0,8.000000,302.0,16.0,20.0,3815.0,112.0,190.0
271,Mercedes-Benz,S430 4dr,Sedan,Europe,Rear,"$74,320","$69,168",4.3,8.000000,275.0,18.0,26.0,4160.0,122.0,203.0
272,Mercedes-Benz,S500 4dr,Sedan,Europe,All,"$86,970","$80,939",5.0,8.000000,302.0,16.0,24.0,4390.0,122.0,203.0
273,Mercedes-Benz,SL500 convertible 2dr,Sports,Europe,Rear,"$90,520","$84,325",5.0,8.000000,302.0,16.0,23.0,4065.0,101.0,179.0
274,Mercedes-Benz,SL55 AMG 2dr,Sports,Europe,Rear,"$121,770","$113,388",5.5,8.000000,493.0,14.0,21.0,4235.0,101.0,179.0
275,Mercedes-Benz,SL600 convertible 2dr,Sports,Europe,Rear,"$126,670","$117,854",5.5,12.000000,493.0,13.0,19.0,4429.0,101.0,179.0
276,Mercedes-Benz,SLK230 convertible 2dr,Sports,Europe,Rear,"$40,320","$37,548",2.3,4.000000,192.0,21.0,29.0,3055.0,95.0,158.0
277,Mercedes-Benz,SLK32 AMG 2dr,Sports,Europe,Rear,"$56,170","$52,289",3.2,6.000000,349.0,17.0,22.0,3220.0,95.0,158.0
278,Mercedes-Benz,C240,Wagon,Europe,Rear,"$33,780","$31,466",2.6,6.000000,168.0,19.0,25.0,3470.0,107.0,179.0
279,Mercedes-Benz,E320,Wagon,Europe,Rear,"$50,670","$47,174",3.2,6.000000,221.0,19.0,27.0,3966.0,112.0,190.0
280,Mercedes-Benz,E500,Wagon,Europe,All,"$60,670","$56,474",5.0,8.000000,302.0,16.0,24.0,4230.0,112.0,190.0
290,Mitsubishi,Endeavor XLS,SUV,Asia,All,"$30,492","$28,330",3.8,6.000000,215.0,17.0,21.0,4134.0,109.0,190.0
291,Mitsubishi,Montero XLS,SUV,Asia,All,"$33,112","$30,763",3.8,6.000000,215.0,15.0,19.0,4718.0,110.0,190.0
292,Mitsubishi,Outlander LS,SUV,Asia,Front,"$18,892","$17,569",2.4,4.000000,160.0,21.0,27.0,3240.0,103.0,179.0
293,Mitsubishi,Lancer ES 4dr,Sedan,Asia,Front,"$14,622","$13,751",2.0,4.000000,120.0,25.0,31.0,2656.0,102.0,181.0
294,Mitsubishi,Lancer LS 4dr,Sedan,Asia,Front,"$16,722","$15,718",2.0,4.000000,120.0,25.0,31.0,2795.0,102.0,181.0
295,Mitsubishi,Galant ES 2.4L 4dr,Sedan,Asia,Front,"$19,312","$17,957",2.4,4.000000,160.0,23.0,30.0,3351.0,108.0,191.0
296,Mitsubishi,Lancer OZ Rally 4dr auto,Sedan,Asia,Front,"$17,232","$16,196",2.0,4.000000,120.0,25.0,31.0,2744.0,102.0,181.0
297,Mitsubishi,Diamante LS 4dr,Sedan,Asia,Front,"$29,282","$27,250",3.5,6.000000,205.0,18.0,25.0,3549.0,107.0,194.0
298,Mitsubishi,Galant GTS 4dr,Sedan,Asia,Front,"$25,700","$23,883",3.8,6.000000,230.0,18.0,26.0,3649.0,108.0,191.0
299,Mitsubishi,Eclipse GTS 2dr,Sports,Asia,Front,"$25,092","$23,456",3.0,6.000000,210.0,21.0,28.0,3241.0,101.0,177.0
300,Mitsubishi,Eclipse Spyder GT convertible 2dr,Sports,Asia,Front,"$26,992","$25,218",3.0,6.000000,210.0,21.0,28.0,3296.0,101.0,177.0
301,Mitsubishi,Lancer Evolution 4dr,Sports,Asia,Front,"$29,562","$27,466",2.0,4.000000,271.0,18.0,26.0,3263.0,103.0,179.0
302,Mitsubishi,Lancer Sportback LS,Wagon,Asia,Front,"$17,495","$16,295",2.4,4.000000,160.0,25.0,31.0,3020.0,102.0,181.0
303,Nissan,Pathfinder Armada SE,SUV,Asia,Front,"$33,840","$30,815",5.6,8.000000,305.0,13.0,19.0,5013.0,123.0,207.0
304,Nissan,Pathfinder SE,SUV,Asia,Front,"$27,339","$25,972",3.5,6.000000,240.0,16.0,21.0,3871.0,106.0,183.0
305,Nissan,Xterra XE V6,SUV,Asia,Front,"$20,939","$19,512",3.3,6.000000,180.0,17.0,20.0,3760.0,104.0,178.0
306,Nissan,Sentra 1.8 4dr,Sedan,Asia,Front,"$12,740","$12,205",1.8,4.000000,126.0,28.0,35.0,2513.0,100.0,178.0
307,Nissan,Sentra 1.8 S 4dr,Sedan,Asia,Front,"$14,740","$13,747",1.8,4.000000,126.0,28.0,35.0,2581.0,100.0,178.0

In [33]:
df[df['Origin'].isin(["Asia","Europe"])].head()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,22.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,20.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,18.0,24.0,3880.0,115.0,197.0

Remove all the records (rows) where Weight is above 4000

In [45]:
df[~(df["Weight"]>4000)].shape

(325, 15)

5) Increase all the values of "MPG_City" column by 3

In [46]:
df.head(2)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,17.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,24.0,31.0,2778.0,101.0,172.0

In [47]:
df["MPG_City"]=df["MPG_City"].apply(lambda x:x+3)

In [48]:
df.head()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,20.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,27.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,25.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,23.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,21.0,24.0,3880.0,115.0,197.0

In [49]:
df['MPG_City']=df['MPG_City']+3

In [50]:
df.head()

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265.0,23.0,23.0,4451.0,106.0,189.0
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200.0,30.0,31.0,2778.0,101.0,172.0
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200.0,28.0,29.0,3230.0,105.0,183.0
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270.0,26.0,28.0,3575.0,108.0,186.0
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225.0,24.0,24.0,3880.0,115.0,197.0